### ISSUE TITLE
ufomap在实车环境中的杂点问题。

### ISSUE THREAD

**Issue by bit-lsj** [SYSU-RoboticsLab/FAEL#18]
作者您好，感谢您为开源社区做出的贡献，你的开源代码对我的帮助很大。

现在我在参考您代码中ufomap中建图的部分，**在仿真环境中ufomap表现很好，但是在实际环境中，ufomap出现了飘在半空中的杂乱点，我检查了点云输入，发现并不是点云的噪声**，如图所示。不知您当时跑实车时遇到了这种问题吗？

感谢作者您的耐心解答，期待您的回复。

![image](https://github.com/SYSU-RoboticsLab/FAEL/assets/113875629/885fd7cb-ee73-4b6d-83e7-cf961aeee624)

**Comment by hjlstudy** [comment]
可能是定位误差大了？导致地面点云悬在空中？
